### ISSUE TITLE
Provisional python 3 support

### ISSUE THREAD

**Issue by VikParuchuri** [edx/codejail#33]
I just added provisional python 3 support to my fork of codejail -- https://github.com/VikParuchuri/codejail .  There are some other changes in there as well, though.  

If there is interest, I could refactor the python 3 compatibility changes and submit a PR here at some point.

**Comment by nickjm** [comment]
Since python2 will no longer be supported in a couple years, what's the current status of python3 compatibility?

**Comment by nedbat** [comment]
@nickjm We have a plan to move all of the Open edX code to Python 3, but it will be a long process.  Smaller repos like this one will get converted first.
