### ISSUE TITLE
No Output !

### ISSUE THREAD

**Issue by Kleidi17** [edx/codejail#39]
Hello ! 

When I run the following commands:

import codejail.jail_code
codejail.jail_code.configure('python', '/home/klei/ex/sandboxenv/bin/python', 'klei')
import codejail.safe_exec
codejail.safe_exec.safe_exec("import os\nos.system('ls /etc')", {})

I get no output (no matter what code I try to execute).
If I execute in the safe_exec function the following: print(res.stdout, res.status, res.stderr), I get this result:
('{}', 0, '')

Thanks in advance

**Comment by Kleidi17** [comment]
I do get output when there is an error in the code.

**Comment by nedbat** [comment]
On successful execution, the stdout of the jailed code is not provided to you.  Your os.system call will write to stdout, but it is discarded.  Your code needs to update globals in the global dictionary to return information.

What code are you actually trying to run?  "ls /etc/" won't be very useful :)

**Comment by Kleidi17** [comment]
No specific code actually. I was just trying to get it to work. Even print statements do not produce output and also according to the README the following codejail.safe_exec.safe_exec("import os\nos.system('ls /etc')", {})
should also raise an exception but it doesn't.

The code seems to run because I tried an infinite loop and I got an exception(as it should be according to the cpu time limits).

**Comment by nedbat** [comment]
I'm not sure how else to say this: printed output is not returned to you.  Try this:
```
g = {}
codejail.safe_exec.safe_exec("a = 2+3", g)
print g
```
You will see that g has a key of 'a' with a value of 5.

**Comment by Kleidi17** [comment]
Yes, I get {u'a': 5}. 
I thought the program was supposed to return the output, sorry about that. 
If you have a quick solution about how to get the stdout I will really appreciate it.
Thanks

**Comment by nedbat** [comment]
Depending on what you need from stdout, you can either create a StringIO and assign it to sys.stdout, or you cannot get it.  What code are you trying to run in CodeJail?

**Comment by Kleidi17** [comment]
I am trying to build a website where users can run their own code and get the result back. That's why I need the output and that's why I need it to run in a secure environment.

**Comment by nedbat** [comment]
Here's an example of how to capture stdout so that you can return it as a string from CodeJail:
```
import codejail.safe_exec

g = {}
codejail.safe_exec.safe_exec(
"""\
from cStringIO import StringIO
import sys
sys.stdout = StringIO()

# ----- user code goes here -----
print "Hello, world!"

# ----- end user code

stdout = sys.stdout.getvalue()
""", g)
print g
```

**Comment by Kleidi17** [comment]
Thanks a lot. I'm new to python and I don't know its library very well. Very kind of you for taking the time and showing me how its done.
