### ISSUE TITLE
Does unsafe code raise an exception? 

### ISSUE THREAD

**Issue by goehle** [edx/codejail#40]
I was following the readme for this and under the Using CodeJail section it mentions that the unsafe code should throw an exception.  When I tried it the code did not print out the files in /etc, but it didn't throw an exception either.  I didn't know if I'm incorrectly configured or if things have changed.  One thing I had to do was 
```
codejail.jail_code.configure('python', '<SANDENV>/bin/python','sandbox')
```
instead of the written
```
codejail.jail_code.configure('python', '<SANDENV>/bin/python')
```

**Comment by MeGustas** [comment]
Can you tell me the reason？
Now I'm getting the same problem… so confused
