### ISSUE TITLE
These octal literals are not Python3 compatible. 

### ISSUE THREAD

**Issue by nickjm** [edx/codejail#56]
https://github.com/edx/codejail/blob/64e0ed418252d583f35a363853a01c0a2920d29a/codejail/jail.py#L216

https://stackoverflow.com/questions/1837874/invalid-token-when-using-octal-numbers

Try using "0o" instead of "0"

**Comment by nedbat** [comment]
As it happens, we have a pull request that changes them: https://github.com/edx/codejail/pull/57
